### ISSUE TITLE
Acceptance test, raising exceptions in ActiveMQ

### ISSUE THREAD

**Issue by SimonCropp** [ParticularLabs/NServiceBus.ActiveMQ#1]
Raised by @johnsimons
Migrated from by https://github.com/Particular/NServiceBus/issues/1369

```
2013-07-31 06:59:27,789 [7052] WARN  JetBrains.Container.Log4netDefaultLoggerInitializer - Unhandled exception in current domain: System.Threading.ThreadAbortException: Thread was being aborted.
[16:59:27][Step 6/6]    at Apache.NMS.ActiveMQ.Transport.Tcp.TcpTransport.ReadLoop()
[16:59:27][Step 6/6]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[16:59:27][Step 6/6]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[16:59:27][Step 6/6]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[16:59:27][Step 6/6]    at System.Threading.ThreadHelper.ThreadStart(),    at Apache.NMS.ActiveMQ.Transport.Tcp.TcpTransport.ReadLoop()
[16:59:27][Step 6/6]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[16:59:27][Step 6/6]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
[16:59:27][Step 6/6]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[16:59:27][Step 6/6]    at System.Threading.ThreadHelper.ThreadStart(), (null)
```

**Comment by SimonCropp** [comment]
Raised by @SimonCropp

@johnsimons how do we repro this?

**Comment by SimonCropp** [comment]
Raised by @johnsimons

It seems to be happening at shutdown time when running ActiveMQ transport.
The way I found out about this was by looking through the logs, eg d/l [this](http://builds.particular.net/viewLog.html?buildId=6878&buildTypeId=bt23&tab=buildLog) log and then do a search for "ReadLoop".

I'm not sure if it is reproducible locally.

**Comment by SimonCropp** [comment]
Raised by @danielmarbach

Sorry guys that we don't participate. I'm in vacation

Am 13.08.2013 um 09:52 schrieb Simon Cropp notifications@github.com:
